# Triggers the workflows on push or pull request events but only for the main branch
name: Creates new release when methods are updated automatically
on:
  push:
    branches: [main]
    tags-ignore:
      - '**'
    paths:
      - 'etsy_py/methods.py'
      - 'etsy_py/client.pyi'

  # Allows you to run this workflows manually from the Actions tab
  workflow_dispatch:

# A workflows run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflows contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: Example-test-autorelease-tag
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}